export const PROVINCES = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Gilgit-Baltistan',
  'Azad Kashmir',
  'Islamabad Capital Territory',
];

export const DISTRICTS_BY_PROVINCE = {
  Punjab: [
    'Attock',
    'Bahawalnagar',
    'Bahawalpur',
    'Bhakkar',
    'Chakwal',
    'Chiniot',
    'Dera Ghazi Khan',
    'Faisalabad',
    'Gujranwala',
    'Gujrat',
    'Hafizabad',
    'Jhang',
    'Jhelum',
    'Kasur',
    'Khanewal',
    'Khushab',
    'Lahore',
    'Layyah',
    'Lodhran',
    'Mandi Bahauddin',
    'Mianwali',
    'Multan',
    'Muzaffargarh',
    'Nankana Sahib',
    'Narowal',
    'Okara',
    'Pakpattan',
    'Rahim Yar Khan',
    'Rajanpur',
    'Rawalpindi',
    'Sahiwal',
    'Sargodha',
    'Sheikhupura',
    'Sialkot',
    'Toba Tek Singh',
    'Vehari',
  ],
  Sindh: [
    'Badin',
    'Dadu',
    'Ghotki',
    'Hyderabad',
    'Jacobabad',
    'Jamshoro',
    'Karachi Central',
    'Karachi East',
    'Karachi South',
    'Karachi West',
    'Kashmore',
    'Khairpur',
    'Korangi',
    'Larkana',
    'Malir',
    'Matiari',
    'Mirpur Khas',
    'Naushahro Feroze',
    'Qambar Shahdadkot',
    'Sanghar',
    'Shaheed Benazirabad',
    'Shikarpur',
    'Sukkur',
    'Sujawal',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Thatta',
    'Tharparkar',
    'Umerkot',
  ],
  'Khyber Pakhtunkhwa': [
    'Abbottabad',
    'Bajaur',
    'Bannu',
    'Battagram',
    'Buner',
    'Charsadda',
    'Chitral Lower',
    'Chitral Upper',
    'Dera Ismail Khan',
    'Hangu',
    'Haripur',
    'Karak',
    'Khyber',
    'Kohat',
    'Kohistan Lower',
    'Kohistan Upper',
    'Kolai Palas',
    'Kurram',
    'Lakki Marwat',
    'Lower Dir',
    'Malakand',
    'Mansehra',
    'Mardan',
    'Mohmand',
    'North Waziristan',
    'Nowshera',
    'Orakzai',
    'Peshawar',
    'Shangla',
    'South Waziristan',
    'Swabi',
    'Swat',
    'Tank',
    'Torghar',
    'Upper Dir',
  ],
  Balochistan: [
    'Awaran',
    'Barkhan',
    'Chagai',
    'Dera Bugti',
    'Dukki',
    'Gwadar',
    'Harnai',
    'Hub',
    'Jafarabad',
    'Jhal Magsi',
    'Kachhi',
    'Kalat',
    'Kech',
    'Kharan',
    'Khuzdar',
    'Kohlu',
    'Lasbela',
    'Loralai',
    'Mastung',
    'Musakhel',
    'Nasirabad',
    'Nushki',
    'Panjgur',
    'Pishin',
    'Qila Abdullah',
    'Qila Saifullah',
    'Quetta',
    'Sherani',
    'Sibi',
    'Sohbatpur',
    'Surab',
    'Usta Muhammad',
    'Washuk',
    'Zhob',
    'Ziarat',
  ],
  'Gilgit-Baltistan': [
    'Astore',
    'Diamer',
    'Darel',
    'Tangir',
    'Ghanche',
    'Ghizer',
    'Gilgit',
    'Hunza',
    'Kharmang',
    'Nagar',
    'Shigar',
    'Skardu',
  ],
  'Azad Kashmir': [
    'Bagh',
    'Bhimber',
    'Hattian Bala',
    'Haveli',
    'Jhelum Valley',
    'Kotli',
    'Mirpur',
    'Muzaffarabad',
    'Neelum',
    'Poonch',
    'Sudhnoti',
  ],
  'Islamabad Capital Territory': ['Islamabad'],
};

export const SOIL_TYPES = ['Sandy', 'Clay', 'Loamy', 'Silty', 'Peaty', 'Chalky', 'Saline'];
export const CROPPING_SYSTEMS = [
  'Single Crop',
  'Mixed Farming (Crops + Livestock)',
  'Intercropping',
  'Crop Rotation',
];
export const SOIL_SUSTAINABILITY_OPTIONS = [
  'Low - Minimal practices',
  'Medium - Moderate practices',
  'High - Best practices',
];
export const IRRIGATION_OPTIONS = [
  'Drip Irrigation',
  'Sprinkler System',
  'Flood Irrigation',
  'Bore Well',
  'Canal Water',
  'Rain Fed',
];

export const NAME_PATTERN = /^[A-Za-z][A-Za-z\s'.-]{1,59}$/;
export const FARM_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9\s'.-]{1,79}$/;
export const LOCATION_PATTERN = /^[A-Za-z][A-Za-z\s'.-]{1,79}$/;
export const VILLAGE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9\s'.-]{1,79}$/;
export const DECIMAL_INPUT_PATTERN = /^\d*\.?\d*$/;
export const NUMERIC_INPUT_FIELDS = new Set([
  'sizeAcres',
  'phLevel',
  'nitrogen',
  'phosphorus',
  'potassium',
  'rainfall',
  'humidity',
  'temperature',
]);

export const INITIAL_FARM_FORM = {
  farmerName: '',
  farmName: '',
  sizeAcres: '',
  province: '',
  district: '',
  village: '',
  soilType: 'Loamy',
  phLevel: '6.5',
  nitrogen: '0',
  phosphorus: '0',
  potassium: '0',
  rainfall: '0',
  humidity: '0',
  temperature: '0',
  croppingSystem: '',
  soilSustainability: '',
  irrigationFacilities: [],
};

export const getDistrictOptions = (province) => DISTRICTS_BY_PROVINCE[province] || [];
